on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: pip install --upgrade pipenv>=2018.10.9
    - run: pipenv install --deploy --dev
    - run: pipenv graph
    - run: pipenv run black --check .
